# This is a basic workflow to help you get started with Actions
name: AWS Lambda & API gateway deployment demo

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repo under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      # Installs Python
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      # Installs PIP
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
      # Configures AWS credentials from github secrets - DO I NEED THIS IF I HAVE IT IN SAM build?
      # - name: Configure AWS Credentials
      #   uses: aws-actions/configure-aws-credentials@v1
      #   with:
      #     aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
      #     aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      #     aws-region: us-east-1
      # Build using SAM
      - name: SAM Build
        uses: youyo/aws-sam-action/python3.8@v2
        with:
          sam_command: build
        env:
          AWS_ACCESS_KEY_ID: {{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: {{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: us-east-1
      # Deploy on AWS
      - name: SAM deploy
        uses: youyo/aws-sam-action/python3.8@v2
        with:
          sam_command: 'deploy --stack-name myApp --no-fail-on-empty-changeset'
        env:
          AWS_ACCESS_KEY_ID: {{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: {{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: us-east-1


## This is the ORIGINAL deploy.yml - commented for educational purposes
# name: CI

# # Controls when the action will run. 
# on:
#   # Triggers the workflow on push or pull request events but only for the master branch
#   push:
#     branches: [ master ]
#   pull_request:
#     branches: [ master ]

#   # Allows you to run this workflow manually from the Actions tab
#   workflow_dispatch:

# # A workflow run is made up of one or more jobs that can run sequentially or in parallel
# jobs:
#   # This workflow contains a single job called "build"
#   build:
#     # The type of runner that the job will run on
#     runs-on: ubuntu-latest

#     # Steps represent a sequence of tasks that will be executed as part of the job
#     steps:
#       # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
#       - uses: actions/checkout@v2

#       # Runs a single command using the runners shell
#       - name: Run a one-line script
#         run: echo Hello, world!

#       # Runs a set of commands using the runners shell
#       - name: Run a multi-line script
#         run: |
#           echo Add other actions to build,
#           echo test, and deploy your project.
